#include "jdata.h"

enum Data {JIMAGE, JANIMATION, JFONT, JSOUND};
enum State {MENU, PLAY, PAUSE, STORY, EXIT};
enum Position {CENTER = -1};
enum Targets {LMENU, LPLAY};

enum LevelData {DATA_MAINMENU};

// Data IDs
enum Data_Ids {
    ID_DATA_SPLASH, ID_DATA_BACKGROUND, ID_DATA_GRID,
    
    ID_MAINMENU, ID_MAINMENU_PLAY, ID_MAINMENU_ARCADE, ID_MAINMENU_SETTINGS, ID_MAINMENU_EXIT, ID_MAINMENU_TEST,
    
    ID_PLAY, ID_PLAY_PLAYER, ID_PLAY_TIMER, ID_PLAY_SCORE, ID_PLAY_HISCORE, ID_PLAY_COINS, ID_PLAY_OBJECT,
    ID_PLAY_OBJECT2, ID_PLAY_OBJECT3, ID_PLAY_OBJECT4, ID_PLAY_COIN, ID_PLAY_DEBUG,
    
    ID_GAMEOVER, ID_GAMEOVER_TEXT, ID_GAMEOVER_PLAY, ID_GAMEOVER_EXIT,
    
    ID_SETTINGS, ID_SETTINGS_PAGE, ID_SETTINGS_1, ID_SETTINGS_2, ID_SETTINGS_3, ID_SETTINGS_4, ID_SETTINGS_5, ID_SETTINGS_BACK,

    ID_SOUND, ID_SOUND_JUMP, ID_SOUND_MENU, ID_SOUND_MUSIC,

    ID_DATA_END
};

Jgame* resize_window(Jgame*);

