#define MAX_WIDTH 3840
#define MAX_HEIGHT 2160

enum Data {JIMAGE, JFONT};
enum State {MENU, PLAY, PAUSE, STORY, EXIT};
enum Position {CENTER = -1};
enum Targets {LMENU, LPLAY};

enum LevelData {DATA_MAINMENU};

// For menu.c
enum Menu_Ids {ID_MAINMENU_BACKGROUND, ID_MAINMENU_PLAY, ID_MAINMENU_ARCADE, ID_MAINMENU_SETTINGS, ID_MAINMENU_EXIT};

// For play.c
enum Play_Ids {ID_PLAY_BACKGROUND, ID_PLAY_PLAYER, ID_PLAY_3, ID_PLAY_2, ID_PLAY_1, ID_PLAY_GO, ID_PLAY_SCORE, ID_PLAY_HISCORE, ID_PLAY_OBJECT, ID_PLAY_OBJECT2, ID_PLAY_OBJECT3, ID_PLAY_OBJECT4};

// For gameover.c
enum Gameover_Ids {ID_GAMEOVER_TEXT, ID_GAMEOVER_PLAY, ID_GAMEOVER_EXIT};
